# %pip install googletrans==3.1.0a0
from doctest import OutputChecker
from googletrans import Translator
import pandas as pd

translator = Translator()

def back_translate(text: str, num_lang=10):
    """
    Create a list of sentences generated by back translation through up to 10 intermediate languages
    :param text: str, input
    :param num_lang: interger, number of intermediate languages, no larger than 10
    :return: list, result
    """
    lang_inter = ['en','es','ja',"zh-cn","ca",'ar','fi','el','cs','th']
    lang_inter = lang_inter[:num_lang]
    backtrans = [text]
    for lang in lang_inter:
        trans1 = translator.translate(text, src='fr', dest=lang)
        trans2 = translator.translate(trans1.text, src=lang, dest='fr')
        backtrans.append(trans2.text)

    return  list({}.fromkeys(backtrans).keys()) #Only keep the unique results of backtranslations 

def back_trans_train(df: pd.DataFrame, labels:list, num_lang=10):
    """
    Augment train set by back translation
    :param df: DataFrame, trainset
    :param label: list of labels need to be augmented
    :param num_lang: interger, number of intermediate languages, no larger than 10
    :return: df, result
    """
    df1=df.copy()
    df1['ACTIVITE']=df1.apply(lambda x: back_translate(x.ACTIVITE,num_lang) if (x.NAF2_CODE in labels) else x.ACTIVITE,axis=1)
    
    return df1.explode('ACTIVITE')
